name: batrack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  
  - pytorch=2.1.1
  - torchvision=0.16.1
  - pytorch-cuda=11.8

  - pyyaml
  - setuptools
  - pip
  